"""init: add agent_sessions, audit_logs, approval_records

Revision ID: e15a188c1e58
Revises: 
Create Date: 2026-05-26 21:51:12.594023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15a188c1e58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('task_description', sa.Text(), nullable=False, comment='用户输入的自然语言任务描述'),
    sa.Column('session_status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'APPROVAL_PENDING', name='session_status_enum', create_constraint=True), nullable=False, comment='会话当前状态'),
    sa.Column('current_step', sa.Integer(), nullable=False, comment='当前执行到的步骤数'),
    sa.Column('total_steps', sa.Integer(), nullable=False, comment='规划的总步骤数'),
    sa.Column('execution_log', sa.JSON(), nullable=True, comment='执行日志摘要（JSON 格式），保存核心步骤的快照'),
    sa.Column('llm_cost', sa.Numeric(precision=10, scale=6), nullable=False, comment='本次会话的 LLM API 调用总费用（USD）'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='实际开始执行时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='执行完成时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误消息'),
    sa.Column('session_tag', sa.String(length=64), nullable=True, comment='人工可读的会话标签（可选）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（数据库生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（数据库生成）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_session_status'), 'agent_sessions', ['session_status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联的会话 ID'),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='此日志属于执行过程中的第几步'),
    sa.Column('action_type', sa.String(length=64), nullable=False, comment='操作类型：navigate / click / type / screenshot / think / finish / error'),
    sa.Column('action_input', sa.JSON(), nullable=True, comment='操作的输⼊参数（如点击的目标元素、导航的 URL）'),
    sa.Column('action_output', sa.JSON(), nullable=True, comment='操作的输出结果（如截图路径、执行状态）'),
    sa.Column('is_high_risk', sa.Boolean(), nullable=False, comment='是否被标记为高危操作'),
    sa.Column('risk_reason', sa.Text(), nullable=True, comment='高危标记的原因描述'),
    sa.Column('approved', sa.Boolean(), nullable=True, comment='高危操作是否已通过人类审批（None=未审批，True=已通过，False=已拒绝）'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='操作是否执行成功'),
    sa.Column('error_detail', sa.Text(), nullable=True, comment='操作失败时的详细错误'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False, comment='操作执行耗时（毫秒）'),
    sa.Column('action_taken_at', sa.DateTime(timezone=True), nullable=True, comment='操作的原始执行时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（数据库生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（数据库生成）'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_table('approval_records',
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联的会话 ID'),
    sa.Column('audit_log_id', sa.Integer(), nullable=True, comment='触发审批的那条审计日志 ID'),
    sa.Column('risk_type', sa.String(length=64), nullable=False, comment='高危类型：sensitive_url / financial_action / file_operation / delete_action / custom'),
    sa.Column('risk_description', sa.Text(), nullable=False, comment='面向人类的危险操作描述，会展示在 Vue 3 审批弹窗中'),
    sa.Column('risk_score', sa.Integer(), nullable=False, comment='危险等级评分（0-100），越高越危险'),
    sa.Column('action_context', sa.JSON(), nullable=True, comment='操作时的完整上下文快照（URL、页面标题、截图路径等）'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'EXPIRED', name='approvalstatus'), nullable=False, comment='审批状态'),
    sa.Column('responded_at', sa.DateTime(), nullable=True, comment='人类操作员响应时间'),
    sa.Column('response_note', sa.Text(), nullable=True, comment='人类操作员的备注（可选）'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='审批超时时间，超过此时间自动标记为 EXPIRED'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（数据库生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间（数据库生成）'),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_records_session_id'), 'approval_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_records_session_id'), table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_sessions_session_status'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
